# Matrix and Hadamard Product

👨‍💻 **Arjun Adhikari**, June 12, 2019

This is perphaps one operation that we would use quite frequently in ML/DL model. We should remember few things about multiplication.  

- $ C = AB $ is only defined when the second dimension of $ A $ matches the first dimension of $ B $.
- Firther, if $ A $ is of shape (m,n) and $ B $ of shape (n,p), then $ C $ is of shape (m, p).
- This operation is concretely defined as $ Cij =  \sum_{k} A_{i,k}B_{k,j} $.
    - $ C_{ij} $ is computed by taking the dot product of $ i-th $ row of $ A $ with $ j-th $ column of $ B $.
- A more useful method to think of matrix multiplication is as **linear combination of columns** of $ A $ weighted b column entries of $ B $.  

 ![Illustration](https://i.ibb.co/KGmfFWS/unnamed.png)  
 [Image Credit](https://www.mpcm.org/visualizing-matrix-multiplication-as-a-linear-combination-eli-benderskys-website/)

In [1]:
import numpy as np

Loading arbitary elements into matrices $ A $ and $ B $.

In [2]:
A = np.random.randint(low=11, high=20, size=9).reshape(3,3)
B = np.random.randint(low=41, high=50, size=9).reshape(3,3)

print(A.shape)
print(B.shape)

(3, 3)
(3, 3)


In [3]:
print(A,B, sep='\n\n')

[[15 15 18]
 [11 18 12]
 [14 15 12]]

[[43 49 43]
 [48 48 46]
 [45 41 41]]


### Dot Product

##### Method One

In [4]:
print(np.dot(A,B))

[[2175 2193 2073]
 [1877 1895 1793]
 [1862 1898 1784]]


##### Method Two

In [5]:
print(np.matmul(A,B))

[[2175 2193 2073]
 [1877 1895 1793]
 [1862 1898 1784]]


### Element wise Multiplication : Hadamard Product

In [6]:
print(A*B)

[[645 735 774]
 [528 864 552]
 [630 615 492]]
