# Matrices and Tensors

👨‍💻 **Arjun Adhikari**, June 12, 2019

### 1. Scalars and Vectors

- **Scalars** is a _single number_, denoted as x.
- **Vectors** is an _array of scalars_, denoted by x.
    - Thus a vector has $ n $ scalars $ x1, x2, x3, ... xn $.
    - Note that indexing here begins with 1, unlike Python (where it begins with 0).

In [1]:
import numpy as np

In [2]:
x1 = np.array([4,5,6])
print(x1)

[4 5 6]


**It's a row vector**, so accessing the index will give a element.

In [3]:
print(x1[0])

4


In [4]:
print(x1.shape)

(3,)


It has three rows and a column.

### Representing as Column Vector

In [5]:
x = np.array([[4],[5],[6]])
print(x)

[[4]
 [5]
 [6]]


In [6]:
print(x.shape)

(3, 1)


**It's a column vector**, so accessing the index will give a row.  
It is treated as two dimensional matrix.

In [7]:
print(x[0])

[4]


In [8]:
print(x[0][0])

4


If we want to flatten the column matrix into a row, then:

In [9]:
print(x.reshape((-1,))) 

[4 5 6]


Put -1 if we're unknown about the no of rows.

#### Reshaping $ 4 * 1 $ Matrix to $ 2 * 2 Matrix $

In [10]:
x = np.arange(4).reshape((4,1))
print(x)

[[0]
 [1]
 [2]
 [3]]


In [11]:
print(x.reshape((-1,2)))

[[0 1]
 [2 3]]


### 2. Matrices and Tensors

- **Matrix** is the **2D array** of scalars, denoted by X.
    - It has m rows and n columns denoted by $ m*n $ matrix.
    - If $ m = n $, then the matrix is **square matrix**.

- **Tensor** is an **array with more than 2 axes**, denoted by X.
    - Think of Tensor as a generalization of an array with more than 2 axes.

##### Matrix

In [12]:
x = np.array([[4,5,6],[7,8,9]])
print(x)

[[4 5 6]
 [7 8 9]]


In [13]:
print(x.shape)

(2, 3)


It is 2*3 matrix.

##### Tensor

In [14]:
x = np.array([[[1,2,3],[4,5,6]],[[4,7,8],[3,8,9]]])
print(x)

[[[1 2 3]
  [4 5 6]]

 [[4 7 8]
  [3 8 9]]]


In [15]:
print(x.shape)

(2, 2, 3)


Let's access second column element of first row in second depth.

In [16]:
print(x[1,0,1])

7


### 3. Transpose

For a 2D matrix, transpose can be obtained as $ (A^T)_{ij} = A_{ji} $.

For a vector, transpose makes the column vector into a row. Thus a column vector can also be represented as $ x = [x_{1}, x_{2}, x_{3}]^T $

In [17]:
x = np.arange(1,10).reshape((3,3))
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### Method One

In [18]:
print(x.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


##### Method Two

In [19]:
print(np.transpose(x))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### $ 4*1 $ Matrix into $ 1*4 $ Matrix

In [20]:
x = np.arange(1,5).reshape((4,1))
print(x)

[[1]
 [2]
 [3]
 [4]]


In [21]:
print(np.transpose(x))

[[1 2 3 4]]
