# Arithmetic Operations

✍ **Arjun Adhikari**, May 31, 2019

In [1]:
import numpy as np

Operations: 
    1. Addition
    2. Multiplication
    3. Subtraction
    4. Division
    5. Squaring

In [2]:
x = np.random.randint(low=0, high=20, size=10)
y = np.random.randint(low=0, high=20, size=10)

In [3]:
print(' x : {} \n y : {}'.format(x,y))

 x : [10 11 18  8 16 13 12 15  1 15] 
 y : [ 4 11 10  7 10  6 18 19  4  6]


In [4]:
print(x+2)

[12 13 20 10 18 15 14 17  3 17]


In [5]:
print(x+y)

[14 22 28 15 26 19 30 34  5 21]


In [6]:
print(x-y)

[ 6  0  8  1  6  7 -6 -4 -3  9]


In [7]:
print(x*y)

[ 40 121 180  56 160  78 216 285   4  90]


In [8]:
print(x**y)

[     10000 1843829075 1349403648    2097152          0    4826809
          0  198698543          1   11390625]


In [9]:
print(x/y)

[2.5        1.         1.8        1.14285714 1.6        2.16666667
 0.66666667 0.78947368 0.25       2.5       ]


If result the divider is 0, it throws exception.