# Bitwise Operations

✍ **Arjun Adhikari**, May 31, 2019

In [1]:
import numpy as np

x = np.array([0,1,0,1], dtype=np.uint8)
y = np.array([0,0,1,1], dtype=np.uint8)

Operations:  
    1. Bitwise AND Operation  
    2. Bitwise OR Operation  
    3. Bitwise XOR Operation  
    4. Bitwise NOT Operation  

In [2]:
print(np.bitwise_and(x,y))

[0 0 0 1]


In [3]:
print(np.bitwise_or(x,y))

[0 1 1 1]


In [4]:
print(np.bitwise_xor(x,y))

[0 1 1 0]


In [5]:
print(np.bitwise_not(x))

[255 254 255 254]


Here, the binary equivaluent of the number is complemented, so result is a bit strange for Bitwise NOT operation.