# Linear Algebra - Zero

✍ **Arjun Adhikari**, May 31, 2019

In [1]:
import numpy as np

In [2]:
a = np.random.randint(low=1, high=10, size=23)
print(a)

[6 1 1 8 9 8 9 5 2 5 9 3 3 8 8 3 8 4 2 7 8 4 5]


In [3]:
print(a)

[6 1 1 8 9 8 9 5 2 5 9 3 3 8 8 3 8 4 2 7 8 4 5]


Simple Indexing like arrays : 

In [4]:
print(a[1:])

[1 1 8 9 8 9 5 2 5 9 3 3 8 8 3 8 4 2 7 8 4 5]


In [5]:
a = np.random.rand(3,4,3)
print(a)


[[[0.28808112 0.78849252 0.74847901]
  [0.17112011 0.19672647 0.51761621]
  [0.96707857 0.54618039 0.83976464]
  [0.21703564 0.18291935 0.03407744]]

 [[0.08089148 0.22545696 0.65485635]
  [0.62968919 0.56737765 0.40684166]
  [0.84679229 0.7850405  0.3816046 ]
  [0.65538763 0.42018083 0.27669692]]

 [[0.25705517 0.24283085 0.55406709]
  [0.91367291 0.89714733 0.73688393]
  [0.44294135 0.21198479 0.16865749]
  [0.3691309  0.59437176 0.31976832]]]


## Extracting a submatrix

In [6]:
print(a[:,:,1])

[[0.78849252 0.19672647 0.54618039 0.18291935]
 [0.22545696 0.56737765 0.7850405  0.42018083]
 [0.24283085 0.89714733 0.21198479 0.59437176]]


In [7]:
a = np.arange(25)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [8]:
b = a.reshape(5,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Let's take minor of ```a00```.

In [9]:
print(b[1:,1:])

[[ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


## Modify elements

In [10]:
b[1,3] = 10 
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7 10  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Identity Matrix

In [11]:
I = np.identity(4, dtype=np.uint8)
print(I)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Also can be created like this:

In [12]:
I = np.eye(4, dtype=np.uint8)
print(I)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## Matrix of Ones

In [13]:
one = np.ones((4,4), dtype=np.uint8)
print(one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Alternatively, 

In [14]:
one = np.full((4,4), dtype=np.uint8, fill_value=1)
print(one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## Zero Matrix

In [15]:
zero = np.zeros((4,4), dtype=np.uint8)
print(zero)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
